version: '3.8'
services:
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./data/db_data:/usr/data
        ports:
            - 3306:3306
    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
        restart: unless-stopped
        volumes: 
            - ./src/mikromed:/var/www/html/            
            - ./data/apache_log:/var/log/apache2
        ports:
            - 80:80
        depends_on: 
            - db    
    # Caching
    redis:
        image: redis:alpine
        command:
        - /bin/sh
        - -c
        # - Double dollars, so that the variable is not expanded by Docker Compose
        # - Surround by quotes, so that the shell does not split the password
        # - The ${variable:?message} syntax causes shell to exit with a non-zero
        #   code and print a message, when the variable is not set or empty
        - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
        environment: 
            REDIS_PASSWORD: ${REDISPASS}
        volumes:
        - ./data/redis/data:/data
        - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
        - "6379:6379"
volumes:
    data:
    src:
    
    